language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t aavish/devdocker-react-hooks -f Dockerfile.dev .

scripts:
  - docker run -e CI=true aavish/devdocker-react-hooks npm run test
